server:
  port: ${PORT:8081}
message: Gateway configuration. Server is alive for DEV profile

spring:
  eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka
  cloud:
    gateway:
      routes:
        - id: movieRoute 				#Identifico la ruta del service de Movie
          uri: lb://movie-service 		#URL para el redirect segun lo definido en el predicate / lb: loadbalancer
          predicates: 					#Reglas de análisis de una request
            - Path=/movies/**
        - id: catalogRoute 				#Identifico la ruta del service de Catalog
          uri: lb://catalog-service 	#URL para el redirect segun lo definido en el predicate
          predicates: 					#Reglas de análisis de una request
            - Path=/catalog/**

info:
  app:
    name: gateway-service
    description: Gateway Service
    version: 1.0.0
