server:
  port: 8080
  
spring:
  cloud:
    gateway:
      routes:
        - id: movieRoute 						      #Identifico la ruta del service de Movie
          uri: lb://movie-service 		#URL para el redirect segun lo definido en el predicate
          predicates: 							      #Reglas de análisis de una request
            - Path=/movies/**
        - id: catalogRoute 					      #Identifico la ruta del service de Catalog
          uri: lb://catalog-service 		#URL para el redirect segun lo definido en el predicate
          predicates: 							      #Reglas de análisis de una request
            - Path=/catalog/**
  eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka
