server:
  port: 8081
  
spring:
<<<<<<< HEAD
  eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka
  cloud:
    gateway:
      routes:
        - id: movieRoute 				#Identifico la ruta del service de Movie
          uri: lb://movie-service 		#URL para el redirect segun lo definido en el predicate / lb: loadbalancer
          predicates: 					#Reglas de an치lisis de una request
            - Path=/movies/**
        - id: catalogRoute 				#Identifico la ruta del service de Catalog
          uri: lb://catalog-service 	#URL para el redirect segun lo definido en el predicate
          predicates: 					#Reglas de an치lisis de una request
            - Path=/catalog/**
=======
    cloud:
      gateway:
        routes:
          - id: movieRoute 				#Identifico la ruta del service de Movie
            uri: lb://movie-service 		#URL para el redirect segun lo definido en el predicate / lb: loadbalancer
            predicates: 					#Reglas de an치lisis de una request
              - Path=/movies/**
          - id: catalogRoute 				#Identifico la ruta del service de Catalog
            uri: lb://catalog-service 	#URL para el redirect segun lo definido en el predicate
            predicates: 					#Reglas de an치lisis de una request
              - Path=/catalog/**
>>>>>>> 18055be6867fa7c946ed317ef4c9e55595a6e210

info:
  app:
    name: gateway-service
    description: Gateway Service
    version: 1.0.0
