server:
  port: 8080
  
spring:
  cloud:
    gateway:
      routes:
        - id: movieRoute 						#Identifico la ruta del service de Movie
          uri: http://localhost:8082/ 		#URL para el redirect segun lo definido en el predicate
          predicates: 							#Reglas de análisis de una request
            - Path=/movies/**
        - id: catalogRoute 					#Identificando la ruta del service de producto
          uri: http://localhost:8084/ 		#URL para el redirect segun lo definido en el predicate
          predicates: 							#Reglas de análisis de una request
            - Path=/catalog/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
